version: '3'

services:
  jenkins:
    image: jenkins/jenkins:jdk21
    container_name: jenkins
    expose:
      - "8080"
  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    expose:
      - "3000"
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - jenkins
      - grafana